### ISSUE TITLE
Invoice action buttons align center

### ISSUE THREAD

**Issue by Meghnawalkover** [Walkover-Web-Solution/Giddh-New-Angular4-App#1518] opened 2018-12-14 10:39 UTC
Intercom icon is overlapping save and other buttons, so align all buttons in left in all invoices

**Comment by mustafa-walkover** [comment] 2018-12-17 10:08
@Meghnawalkover closing this card, as this is not a bug

**Closed** 2021-07-23 05:34 UTC
Labels: white board
