### ISSUE TITLE
Settings Module - Taxes tab (Tax details being updated)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1069] opened 2018-07-16 07:42 UTC
After creating a tax, when user tries to create another tax and enters text in "Unique No." and "Name" text boxes, then the details of the last created tax change as per the text entered by user.

PFA screenshot for details.

ENV: PROD, Test

Please fix this ASAP.

**Comment by sagarnankani** [comment] 2018-07-16 07:42
![change.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46eb9c9b2d8586ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98515be04b9218c4d83bfb98348c3ea2f68.PNG)

**Comment by mustafa-walkover** [comment] 2018-07-16 10:43
please check this card, it is not reproducible for.. it is happening may be due to taxDetail key by API

**Comment by sagarnankani** [comment] 2018-07-16 11:01
@mustafa-walkover I can still replicate this for you on PROD.

**Comment by mustafa-walkover** [comment] 2018-07-16 11:17
@sagarnankani we checked it together, it is not reproducible. Please comment if still persist

**Comment by Eagle-Giddh** [comment] 2018-12-13 10:08
Fixed on prod

**Closed** 2018-12-13 10:08 UTC
Labels: white board
