### ISSUE TITLE
Manage Groups & Accounts - Position of Groups and Accounts

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1384] opened 2018-10-16 11:02 UTC
In "Manage Groups & Accounts" tab, on deleting a group, position of all other Groups and Accounts changes. (In revenue from operation category)

PFA screenshot.
Please fix this ASAP

ENV: PROD

Please make sure this bug is not reproduced on PROD environment ever, as this has been reported a lot of time previously as well.

**Comment by sagarnankani** [comment] 2018-10-16 11:03
![grpseq.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46ef868a308792ebc3abaf51ab57f5973d047d317c05f57b2984b42aef1723025d594eac485d5c45f8fe8a79b4aa2e32db025fb28c341521842f1bbeb98415be04b9298d4782b1bb8b4bc8e82f68.PNG)

**Comment by walkover101** [comment] 2018-12-13 10:45
@mustafa-walkover please check and fix this.

**Comment by mustafa-walkover** [comment] 2019-01-02 08:32
closing this card, duplicate of card #1384

**Closed by mustafa-walkover** 2019-01-02 08:32 UTC
