### ISSUE TITLE
Generate Sales - Create Stock sidebar ("Create New Group" pop up issue)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1226] opened 2018-09-04 08:59 UTC
In Generate Sales module -> Create Stock sidebar, when user attempts to create a new stock group, a separate "Create New Group" pop up window appears. This is incorrect. User should be able to create a new group in the side bar itself.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment] 2018-09-04 09:00
![Screen Shot 2018-09-04 at 2.12.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a37af113294f5a5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd76d5625c16f11a9b0d11db901ba298e4c84b2bb891ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de14854a2133063e07e2431.png)

**Comment by mustafa-walkover** [comment] 2018-09-05 11:51
This is not bug, please count it as TASK.. since sales module deployed on prod, "create new group" working like this

**Comment by mustafa-walkover** [comment] 2018-09-07 06:01
duplicate of card #1225

**Comment by mustafa-walkover** [comment] 2018-09-28 05:37
I have created task in Goodday #390, therefore closing this card

**Closed by mustafa-walkover** 2018-09-28 05:37 UTC
Labels: Task
